[project]
name = "tesseract-python-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "setuptools>=80.9.0",
    "tesseract-robotics>=0.5.1",
    "tesseract-robotics-viewer>=0.5.0",
]
